/**
 * Sample rawRequest
 */
// {
// 	slug: 'submit/232824820221043',
// 	submit_source: 'form',
// 	q4_clientsName: { first: 'Omar', last: 'Beltran' },
// 	q5_clientsDate: { month: '08', day: '31', year: '1999' },
// 	q7_genderIdentification: 'Male',
// 	q8_birthSex: 'Male',
// 	q9_pronouns: 'He/Him',
// 	q10_dominantHand: 'Right',
// 	q11_seizuresHistory: 'No',
// 	q12_ifYes: 'Something here',
// 	q13_primaryCell: { full: '(331) 312-3123' },
// 	q14_primaryContact: 'omar@exhio.com.mx',
// 	q15_primaryContact15: { first: 'Ricardo', last: 'String' },
// 	q16_relationshipTo: 'Work mate',
// 	q25_ifYou: 'No',
// 	q26_ifNo: "I don't have children",
// 	q17_itIs: 'Yes',
// 	q18_secondaryemergencyContact: { first: 'Diego', last: 'Lopez' },
// 	q19_relationshipTo19: 'Work mate',
// 	q20_secondaryemergencyContact20: { full: '(331) 234-1324' },
// 	q21_clientsAddress: {
// 		addr_line1: 'Someone',
// 		addr_line2: 'somewhere',
// 		city: 'Guadalajara',
// 		state: 'Jalisco',
// 		postal: '45650',
// 	},
// 	q22_occupationOr: 'Developer',
// 	q23_howDid: 'Work ',
// 	q24_ifWe: 'Fix my ankle ',
// 	event_id: '1696967092502_232824820221043_7hKHyNa',
// 	validatedNewRequiredFieldIDs:
// 		'{"id_4":"Be","id_5":"08","id_7":"Ma","id_11":"No","id_13":"(3","id_14":"om","id_17":"No","id_18":"Lo","id_19":"Wo","id_20":"(3","id_21":"45","id_22":"De","id_23":"Wo","id_24":"Fi"}',
// 	path: '/submit/232824820221043',
// }

export const propertiesMap = {
	q4_clientsName: 'ClientName',
	q5_clientsBirth: 'ClientDate',
	q7_genderIdentification: 'GenderIdentification',
	q8_birthSex: 'BirthSex',
	q9_pronouns: 'Pronouns',
	q10_dominantHand: 'DominantHand',
	q11_anyHistory: 'SeizuresHistory',
	q12_ifYes: 'SeizuresSummary',
	q13_primaryCell: 'PrimaryContactCell',
	q14_primaryContact: 'PrimaryContactEmail',
	q15_primaryContact15: 'PrimaryContactNoClient',
	q16_relationshipTo: 'PrimaryContactRelation',
	q25_ifYou: 'FillingForChild',
	q26_ifNo: 'ChildExplanation',
	q17_isIt: 'OkayWithTexting',
	q18_secondaryemergencyContact: 'SecondaryContact',
	q19_relationshipTo19: 'SecondaryRelationship',
	q20_secondaryemergencyContact20: 'SecondaryContactCell',
	q21_clientsAddress: 'ClientAddress',
	q22_occupationOr: 'Occupation',
	q23_howDid: 'FindAboutUs',
	q24_ifWe: 'WantedSymptomToDecrease',
	q29_typeA: 'SymptomQuestionnaire',
	q33_whatHave: 'GivenApproaches',
	q34_pleaseList: 'TakingMedications',
	q35_whoIs: 'PrescribingDoctors',
	q36_pleaseList36: 'TakingNoMedications',
	q37_whoIs37: 'NoMedicationsGuidance',
	q38_pleaseList38: 'DietConsiderations',
	q39_pleaseList39: 'RecentHealthProfessionals',
	q40_pleaseList40: 'MedicalProcedures',
	q41_pleaseList41: 'OfficialDiagnoses',
	q43_historyOf: 'BrainInjuryHistory',
	q44_pleaseLet: 'AnythingImportant',
};
